name: Lint PR Title
on:
    [pull_request]


jobs:
  lint-title:
    runs-on: ubuntu-latest
    steps:
      - run: |
          commit_types="(build|chore|ci|docs|feat|fix|perf|refactor|style|test)"
          commit_spaces="(OS1TEAM1|OS1TEAM2|OS2TEAM1|OS2TEAM2|OS2TEAM3|OS2TEAM4)"
          commit_regex="^((${commit_types}(\(.+\))?: (${commit_spaces}\-[0-9]+ \| ))|Merge (remote\-tracking )?branch .* into).*"

          # Check the message
          if [[ "${{ github.event.pull_request.title }}" =~ $commit_regex ]]; then
            echo -e ":white_check_mark: PR title meets CE conventions" >> $GITHUB_STEP_SUMMARY
            exit 0
          fi
        
          echo ":x: PR Title does not meet CE conventions" >> $GITHUB_STEP_SUMMARY
          echo "***********************************************************************"  >> $GITHUB_STEP_SUMMARY                                                                                                                                                      
          echo "Available commit message types: ${commit_types}" >> $GITHUB_STEP_SUMMARY
          echo "Available commit spaces: ${commit_spaces}" >> $GITHUB_STEP_SUMMARY
          echo "  <type>(<scope>): <jira-id> | <description> - <scope> is optional but advised" >> $GITHUB_STEP_SUMMARY
          echo "***********************************************************************" >> $GITHUB_STEP_SUMMARY
          echo "An example of a valid message is: " >> $GITHUB_STEP_SUMMARY
          echo "  feat(StarterErrors): OS1TEAM1-123 | add new exception type" >> $GITHUB_STEP_SUMMARY
          echo "More details at: https://devstack.vwgroup.com/confluence/x/3JBBdg#EnableCEindependentreleaseswithTrunkBasedDevelopment-Gitconventions" >> $GITHUB_STEP_SUMMARY
          
          exit 1
