# Workflow to tag and increase tag
name: custom

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to retrieve commit from'
        required: true

jobs:
  get_commit:
    runs_on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Get Last Commit with Tag
        run: |
          TAG_NAME=${{ github.event.inputs.tag }}
          COMMIT_HASH=$(git rev-list -n 1 $TAG_NAME)
          echo "::set-output name=commit_hash::$COMMIT_HASH"


  print_commit:
    runs_on: ubuntu-latest
    needs: retrieve_commit

    steps:
      - name: Print Last Commit
        run: echo "Last commit with tag ${{ github.event.inputs.tag }} is ${{ needs.retrieve_commit.outputs.commit_hash }}"
