# Workflow to tag and increase tag
name: custom

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to tag the commit with'
        required: false
      service:
        description: 'The service to deploy'
        required: false


jobs:
  get_commit:
    runs-on: ubuntu-latest
    outputs:
      history: ${{steps.get_hash.outputs.history}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Last Tag
        run: |
          export TAG_REGEX="${{ github.event.inputs.tag }}-*"
          echo "$(git tag -l --sort=-v:refname $TAG_REGEX)"
      - name: Tag Commit
        run:
      - name: Get
        id: "get_hash"
        run: |
          TAG_NAME=${{ github.event.inputs.tag }}
          echo "history=$(git log --oneline $TAG_NAME..HEAD)" >> $GITHUB_OUTPUT 


  print_commit:
    runs-on: ubuntu-latest
    needs: get_commit

    steps:
      - name: Print Last Commit
        run: echo "History':' ${{ github.event.inputs.tag }} \n ${{ needs.get_commit.outputs.history }}"
