# Workflow to tag and increase tag
name: custom

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to retrieve commit from'
        required: true

jobs:
  get_commit:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{steps.get_hash.outputs.commit_hash}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Get Last Commit with Tag
        id: "get_hash"
        run: |
          TAG_NAME=${{ github.event.inputs.tag }}
          echo "commit_hash=$(git show-ref -s $TAG_NAME)" >> $GITHUB_OUTPUT 


  print_commit:
    runs-on: ubuntu-latest
    needs: get_commit

    steps:
      - name: Print Last Commit
        run: echo "Last commit with tag ${{ github.event.inputs.tag }} is ${{ needs.get_commit.outputs.commit_hash }}"
