# Workflow to tag and increase tag
name: semantic release plus

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'The service to deploy'
        required: true
        type: choice
        options:
          - "service1"
          - "service2"

jobs:
  install-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install Semantic Release Plus
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm i semantic-release-plus
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SERVICE=${{ github.event.inputs.service }} npx semantic-release-plus --extends=./release.config.js
